name: OpenCADC OpenStack Swift Docker CI

on:
  pull_request:
  push:
  release:

jobs:
  #
  # Package jobs
  #
  package-3_13:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      name: swift
      version: '3.13'
      flavour: slim
#
# End Package Jobs
#
